### PR TITLE
The context_instance argument of render_to_string is deprecated.

### PR DESCRIPTION
**Pull request by collinanderson**
removed RemovedInDjango110Warning

### CODE REVIEW

**Comment by claudep** [comment]
django-contrib-comments still supports Django 1.6. Would it be possible to update the patch to still support 1.6?

**Comment by collinanderson** [comment]
We'll see if this works.

**Comment by collinanderson** [comment]
Excellent. All tests passed this time.

**Comment by claudep** [comment]
Thanks Collin!

**Comment by claudep** [comment]
We might simplify the patch now that Django 1.6 support is dropped. Do you still have access to the initial version?

**Pull request merged**
