### PR TITLE
Adapted initial migration to not cause new migration with Django 4

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
@claudep I've built a custom package from this PR and after installing it inside my Django4 venv and running `manage.py makemigrations` it says `No changes detected`.

+1 from my side.

**Comment by claudep** [comment]
Great, could you please also check that if returning to Django 3.2, the same `No changes detected` is output?

**Comment by atodorov** [comment]
```
(kiwi_django3) [senko@localhost Kiwi]$ pip freeze | grep Django
Django==3.2.11

(kiwi_django3) [senko@localhost Kiwi]$ pip freeze | grep django-contrib-comments
django-contrib-comments @ file:///home/senko/django-contrib-comments/dist/django-contrib-comments-2.1.9.tar.gz

$ ./manage.py makemigrations
No changes detected
```

**Comment by claudep** [comment]
Awesome, thanks!

**Comment by atodorov** [comment]
@claudep do you mind bumping the version on PyPI ?

**Comment by claudep** [comment]
Sure, I'll plan that for the next days.

**Pull request merged**
