### PR TITLE
'url' was deprecated since version 3.1 - re_path is backwards compatible

### PR DESCRIPTION
**Pull request by Jonas-SRB**

### CODE REVIEW

**Comment by claudep** [comment]
Thanks, but please remove the .idea files. And you can directly replace by the `path` syntax.

**Comment by Jonas-SRB** [comment]
> Thanks, but please remove the .idea files. And you can directly replace by the `path` syntax.

Done (I guess, this is my first ever pull request..) Thanks

**Comment by claudep** [comment]
Congratulations :tada:
However, with `path`, you also have to adapt the path syntax.

**Comment by claudep** [comment]
Thanks!

**Pull request merged**
