### PR TITLE
distinguish between comment name and person name in translation

### PR DESCRIPTION
**Pull request by PetrDlouhy**
In czech, there is different word for name of the person "Jméno" and name of the thing "Název". It needs to be differed in the locales.

### CODE REVIEW

**Comment by claudep** [comment]
I understand the problem, but is there an occurrence elsewhere in the code where "Name" is used for a thing? If not, then I'd suggest to simply add a translator comment [1] instead of using pgettext.
[1] https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#comments-for-translators

**Comment by PetrDlouhy** [comment]
There is occurance in main Django project, which overrides this. It was translated as "Jméno" (name for a person) before in django-contrib-comments locale, but the comment form displayed "Název" (name for a thing, which is confusing.

**Comment by claudep** [comment]
Sorry, but could you show me where exactly it is used as "name for a thing" in main Django? I did not find anything after a quick research.

**Comment by PetrDlouhy** [comment]
I taught that it comes from main Django locale (where the translation is in file contrib/auth/locale/cs/LC_MESSAGES/django.po), but in fact it interferes with django-constance application. I am not sure, how the locale framework works in case of more than one translation in .po files, but this is not the correct way.

The translation of "Name" as "Název" (name for a thing) is more common and if the django-contrib-comments locale couldn't be somehow prefered for it's locale, the translation should be introduced with context.

**Comment by claudep** [comment]
OK, makes sense. Pushed in 1cb1d18.
To correct the Czech translation, please go to https://www.transifex.com/projects/p/django-contrib-comments

**Pull request closed without merging**
